### ISSUE TITLE
custom map import error

### ISSUE THREAD

**Issue by WindTi** [carla-simulator/traffic-generation-editor#26]
When I connect to carla, the built-in map can run normally, but when I switch to the custom map, an error is reported:

 File "~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ad_map_access_qgis/ADMapQgsLayers.py", line 261, in __add_lane_surface_layer__
lane_list = ad.map.lane.getLanes()
RuntimeError: Instance not initialized. Forgot to call AdMapAccess::initialize?

Is it that my map is missing necessary elements like lane id etc.

**Comment by fabianoboril** [comment]
@berndgassmann Can you help on this matter?

**Comment by berndgassmann** [comment]
Hi,
from the trace output it indicates that your map wasn't loaded correctly. Can you have a look at the command line output, please? ad-map-access is printing warning and error log messages to the console from where you started qgis. Maybe there one spots more info on the reason for the issue.

To double check if loading of your custom open drive map is actually the issue, you can also try to load your custom xodr map without the traffic generation tool, but directly with the load button of the CARLA ad-map-access plugin. For this, after start of qgis use the LoadMap button of that tool instead of connecting to CARLA (https://ad-map-access.readthedocs.io/en/latest/ad_map_access_qgis/ad_map_access_qgis/). There you then navigate to the folder and select the xodr file of your map.

So how exactly do you "switch" to the custom map? 
Did you try to start CARLA and switch the map there by running:
```
./PythonAPI/util/config.py -m <your-custom-map>
```
and with the custom map loaded into CARLA you then start qgis and connect to Carla?

**Comment by WindTi** [comment]
carla 0.9.12
python3.6.9
ubuntu 18.04

Thanks for your reply, I tried the method you mentioned to directly load the .xodr file through the ad_map_access plugin, and the error is as follows:
2022-03-07T10:20:43     WARNING    Traceback (most recent call last):
              File "/home/wan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ad_map_access_qgis/__init__.py", line 131, in __map_load__
              Globs.log.info("Loading data from " + self.file_name[0] + " ...")
              File "/home/wan/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ad_map_access_qgis/__init__.py", line 99, in __open_map__
              open_drive_content, 0.2, ad.map.intersection.IntersectionType.Unknown, ad.map.landmark.TrafficLightType.UNKNOWN)
             ValueError: Cannot convert from Geo to ECEF: Input point invalid.
I have compared the .xodr file of the map provided by carla with the .xodr of the custom map and it is hard to see a noticeable difference.

**Comment by berndgassmann** [comment]
Do you see any output on the shell from where you started qgis?
I could imagine that there is something wrong/incompatible with the geo reference tag and therefore setting geo reference is failing. In header of Town01 this e.g. look like:
`<geoReference><![CDATA[+proj=tmerc +lat_0=0 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs ]]></geoReference>`
But I am sure, that at the shell you should see more log output from ad-map-access library itself, can you please check this?

**Comment by WindTi** [comment]
Just now I also found that the definition of <geoReference> is missing, thank you very much for your reply, my custom map has been able to run normally

**Comment by WindTi** [comment]
Just now I also found that the definition of <geoReference> is missing, thank you very much for your reply, my custom map has been able to run normally

**Comment by WindTi** [comment]
Just now I also found that the definition of geoReference is missing, thank you very much for your reply, my custom map has been able to run normally
